=== fer2610/XML_SAX/src/main/java/main/XML/reserva.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:reserva="http://www.unison.mx/reserva"
            targetNamespace="http://www.unison.mx/reserva"
            elementFormDefault="qualified">

    <xsd:complexType name="tipoHuesped">
        <xsd:sequence>
            <xsd:element name="nombres" type="xsd:string"/>
            <xsd:element name="apellido" type="xsd:string"/>
            <xsd:element name="pasaporte" type="xsd:string"/>
            <xsd:element name="nacionalidad" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="responsable" type="xsd:boolean" />
    </xsd:complexType>

    <xsd:complexType name="tipoResidentes">
        <xsd:sequence>
           <xsd:element name="residente" type="reserva:tipoHuesped" maxOccurs="2" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoHabita">
        <xsd:sequence>
            <xsd:element name="desde" type="xsd:date"/>
            <xsd:element name="hasta" type="xsd:date"/>
            <xsd:element name="residentes" type="reserva:tipoResidentes"/>
        </xsd:sequence>
        <xsd:attribute name="numero" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="tipoTarjeta">
        <xsd:sequence>
            <xsd:element name="tipo" type="xsd:string"/>
            <xsd:element name="numero" type="xsd:decimal"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="reserva">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="habitaciones" >
                    <xsd:complexType>
                        <xsd:sequence >
                            <xsd:element name="habitacion" type="reserva:tipoHabita"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="mediopago" >
                        <xsd:complexType>
                           <xsd:sequence>
                              <xsd:element name="tarjeta_credito" type="reserva:tipoTarjeta"/>
                           </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="version" type="xsd:integer" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== fer2610/XML_SAX/src/main/java/main/XML/reserva.xml
<?xml version="1.0"?>
<rs:reserva xmlns:rs="http://www.unison.mx/reserva"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
         xsd:schemaLocation="http://www.unison.mx/reserva
                             reserva.xsd" version="1">

    <rs:habitaciones>
        <rs:habitacion numero="202">
            <rs:desde>2009-11-22</rs:desde>
            <rs:hasta>2009-11-24</rs:hasta>
            <rs:residentes>
                <rs:residente responsable="true">
                    <rs:nombres>Pedro</rs:nombres>
                    <rs:apellido>Camacho</rs:apellido>
                    <rs:pasaporte>552321</rs:pasaporte>
                    <rs:nacionalidad>PE</rs:nacionalidad>
                </rs:residente>
                <rs:residente>
                    <rs:nombres>Julia</rs:nombres>
                    <rs:apellido>Urquidi</rs:apellido>
                    <rs:pasaporte>664423</rs:pasaporte>
                    <rs:nacionalidad>BO</rs:nacionalidad>
                </rs:residente>
            </rs:residentes>
        </rs:habitacion>
    </rs:habitaciones>
    <rs:mediopago>
        <rs:tarjeta_credito>
            <rs:tipo>AMEX</rs:tipo>
            <rs:numero>38822050023042</rs:numero>
        </rs:tarjeta_credito>
    </rs:mediopago>
</rs:reserva>
